#version 450

layout(local_size_x = 16, local_size_y = 16) in;

layout(set = 0, binding = 0, rgba32f) uniform readonly image2D u_inputImage;
layout(set = 0, binding = 1, rgba32f) uniform writeonly image2D u_brightImage;

layout(push_constant) uniform PushConstants
{
    float u_bloomThreshold;
};

void main() {
    ivec2 texCoords = ivec2(gl_GlobalInvocationID.xy);
    ivec2 imageSize = imageSize(u_inputImage);
    if (texCoords.x >= imageSize.x || texCoords.y >= imageSize.y) {
        return;
    }

    vec4 color = imageLoad(u_inputImage, texCoords);
    float brightness = dot(color.rgb, vec3(0.2126, 0.7152, 0.0722));
    vec3 bright = brightness > u_bloomThreshold ? color.rgb : vec3(0.0);
    imageStore(u_brightImage, texCoords, vec4(bright, 1.0));
}
