#version 450

layout(local_size_x = 16, local_size_y = 16) in;

layout(set = 0, binding = 0, rgba32f) uniform readonly image2D u_inputImage;
layout(set = 0, binding = 1, rgba32f) uniform writeonly image2D u_outputImage;

layout(push_constant) uniform PushConstants
{
    int u_horizontal;
};

const float weights9[9] = float[](0.016216, 0.054054, 0.1216216, 0.1945946, 0.2270270, 0.1945946, 0.1216216, 0.054054, 0.016216);

void main() {
    ivec2 texCoords = ivec2(gl_GlobalInvocationID.xy);
    ivec2 imageSize = imageSize(u_inputImage);
    if (texCoords.x >= imageSize.x || texCoords.y >= imageSize.y) {
        return;
    }

    vec3 result = vec3(0.0);
    ivec2 direction = u_horizontal == 1 ? ivec2(1, 0) : ivec2(0, 1);

    for (int i = -4; i <= 4; i++) {
        ivec2 sampleCoord = clamp(texCoords + direction * i, ivec2(0), imageSize - 1);
        result += imageLoad(u_inputImage, sampleCoord).rgb * weights9[i + 4];
    }

    imageStore(u_outputImage, texCoords, vec4(result, 1.0));
}
