# Auto-generated by scripts/setup.py — do not edit manually.
# This file provides local SDK paths to CMake without requiring environment variables.

set(VULKAN_SDK "/home/leo/01-Coding/MoleHole2/dependencies/vulkan-sdk/1.4.341.1/x86_64" CACHE PATH "Vulkan SDK root (set by setup.py)" FORCE)
set(VULKAN_INCLUDE_DIR "${VULKAN_SDK}/include" CACHE PATH "" FORCE)
set(VULKAN_LIBRARY "${VULKAN_SDK}/lib/libvulkan.so" CACHE PATH "" FORCE)
