This is makeindex, version 2.17 [TeX Live 2023] (kpathsea + Thai support).
Scanning style file ./book.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file book.acn....done (14 entries accepted, 0 rejected).
Sorting entries....done (55 comparisons).
Generating output file book.acr....done (23 lines written, 0 warnings).
Output written in book.acr.
Transcript written in book.alg.
